format:
  html:
    css: styles.css
    theme: cosmo
    toc: true
metadata-files:
- nbdev.yml
project:
  type: website
website:
  navbar:
    background: primary
    search: true
  open-graph: true
  repo-actions:
  - issue
  sidebar:
    contents:
    - auto: index.ipynb
    - contents:
      - knowledge_base/index.qmd
      - contents:
        - knowledge_base/administrating_domo/index.qmd
        - contents:
          - knowledge_base/administrating_domo/admin_settings_overview/index.qmd
          section: Admin Settings Overview
        - contents:
          - knowledge_base/administrating_domo/approvals/index.qmd
          section: Approvals
        - contents:
          - knowledge_base/administrating_domo/domo_security_options/index.qmd
          section: Domo Security Options
        - contents:
          - knowledge_base/administrating_domo/certifications/index.qmd
          section: Certifications
        - contents:
          - knowledge_base/administrating_domo/controlling_access_in_domo/index.qmd
          - contents:
            - knowledge_base/administrating_domo/controlling_access_in_domo/roles/index.qmd
            section: Roles
          - contents:
            - knowledge_base/administrating_domo/controlling_access_in_domo/user_and_group_management/index.qmd
            section: User And Group Management
          section: Controlling Access In Domo
        - contents:
          - knowledge_base/administrating_domo/governance_tools/index.qmd
          section: Governance Tools
        - contents:
          - knowledge_base/administrating_domo/implementing_sso/index.qmd
          section: Implementing SSO
        - contents:
          - knowledge_base/administrating_domo/specifying_company_settings/index.qmd
          section: Specifying Company Settings
        - contents:
          - knowledge_base/administrating_domo/workflows/index.qmd
          section: Workflows
        section: Administrating Domo
      - contents:
        - knowledge_base/connecting_data_to_domo/index.qmd
        - contents:
          - knowledge_base/connecting_data_to_domo/connectors/index.qmd
          - contents:
            - knowledge_base/connecting_data_to_domo/connectors/database_connectors/index.qmd
            section: Database Connectors
          - contents:
            - knowledge_base/connecting_data_to_domo/connectors/api_connectors/index.qmd
            section: API Connectors
          - contents:
            - knowledge_base/connecting_data_to_domo/connectors/available_custom_connectors/index.qmd
            section: Available Custom Connectors
          - contents:
            - knowledge_base/connecting_data_to_domo/connectors/file_connectors/index.qmd
            section: File Connectors
          - contents:
            - knowledge_base/connecting_data_to_domo/connectors/general_connect_info/index.qmd
            section: General Connect Info
          - contents:
            - knowledge_base/connecting_data_to_domo/connectors/partition_connectors/index.qmd
            section: Partition Connectors
          - contents:
            - knowledge_base/connecting_data_to_domo/connectors/writeback_connectors/index.qmd
            section: Writeback Connectors
          section: Connectors
        - contents:
          - knowledge_base/connecting_data_to_domo/other_connection_methods/index.qmd
          section: Other Connection Methods
        - contents:
          - knowledge_base/connecting_data_to_domo/workbench/index.qmd
          - contents:
            - knowledge_base/connecting_data_to_domo/workbench/workbench_4/index.qmd
            section: Workbench 4
          - contents:
            - knowledge_base/connecting_data_to_domo/workbench/workbench_5/index.qmd
            section: Workbench 5
          - contents:
            - knowledge_base/connecting_data_to_domo/workbench/workbench_51/index.qmd
            section: Workbench 5.1
          - contents:
            - knowledge_base/connecting_data_to_domo/workbench/workbench_52/index.qmd
            section: Workbench 5.2
          section: Workbench
        - contents:
          - knowledge_base/connecting_data_to_domo/cloud_amplifier/index.qmd
          section: Cloud Amplifier
        section: Connecting Data To Domo
      - contents:
        - knowledge_base/consuming_data_in_domo/index.qmd
        - contents:
          - knowledge_base/consuming_data_in_domo/exporting_cards_and_dashboards/index.qmd
          section: Exporting Cards And Dashboards
        - contents:
          - knowledge_base/consuming_data_in_domo/interacting_with_cards_and_dashboards/index.qmd
          section: Interacting With Cards And Dashboards
        section: Consuming Data In Domo
      - contents:
        - knowledge_base/creating_content_in_domo/index.qmd
        - contents:
          - knowledge_base/creating_content_in_domo/beast_mode/index.qmd
          section: Beast Mode
        - contents:
          - knowledge_base/creating_content_in_domo/card_and_dashboard_management/index.qmd
          section: Card And Dashboard Management
        - contents:
          - knowledge_base/creating_content_in_domo/notebook_cards/index.qmd
          section: Notebook Cards
        - contents:
          - knowledge_base/creating_content_in_domo/doc_cards/index.qmd
          section: Doc Cards
        - contents:
          - knowledge_base/creating_content_in_domo/poll_cards/index.qmd
          section: Poll Cards
        - contents:
          - knowledge_base/creating_content_in_domo/visualization_cards/index.qmd
          - contents:
            - knowledge_base/creating_content_in_domo/visualization_cards/chart_properties/index.qmd
            section: Chart Properties
          - contents:
            - knowledge_base/creating_content_in_domo/visualization_cards/chart_types/index.qmd
            section: Chart Types
          - contents:
            - knowledge_base/creating_content_in_domo/visualization_cards/analyzer/index.qmd
            section: Analyzer
          - contents:
            - knowledge_base/creating_content_in_domo/visualization_cards/powering_your_card/index.qmd
            section: Powering Your Card
          - contents:
            - knowledge_base/creating_content_in_domo/visualization_cards/visualization_card_details_view_actions/index.qmd
            section: Visualization Card Details View Actions
          section: Visualization Cards
        - contents:
          - knowledge_base/creating_content_in_domo/sharing_access_to_cards_and_dashboards/index.qmd
          section: Sharing Access To Cards And Dashboards
        - contents:
          - knowledge_base/creating_content_in_domo/sumo_cards/index.qmd
          section: Sumo Cards
        - contents:
          - knowledge_base/creating_content_in_domo/variables/index.qmd
          section: Variables
        section: Creating Content In Domo
      - contents:
        - knowledge_base/creating_custom_visualizations/index.qmd
        - contents:
          - knowledge_base/creating_custom_visualizations/available_apps/index.qmd
          section: Available Apps
        - contents:
          - knowledge_base/creating_custom_visualizations/publish_in_the_appstore/index.qmd
          section: Publish in the Appstore
        - contents:
          - knowledge_base/creating_custom_visualizations/explore_the_appstore/index.qmd
          section: Explore the Appstore
        section: Creating Custom Visualizations
      - contents:
        - knowledge_base/distributing_domo_content/index.qmd
        - contents:
          - knowledge_base/distributing_domo_content/domo_everywhere/index.qmd
          section: Domo Everywhere
        - contents:
          - knowledge_base/distributing_domo_content/plugins_for_sharing_domo_content/index.qmd
          section: Plugins For Sharing Domo Content
        - contents:
          - knowledge_base/distributing_domo_content/publication_groups/index.qmd
          section: Publication Groups
        - contents:
          - knowledge_base/distributing_domo_content/publications_slideshows/index.qmd
          section: Publications (Slideshows)
        - contents:
          - knowledge_base/distributing_domo_content/scheduled_reports/index.qmd
          section: Scheduled Reports
        - contents:
          - knowledge_base/distributing_domo_content/microsoft_office_addins/index.qmd
          section: Microsoft Office Add-ins
        section: Distributing Domo Content
      - contents:
        - knowledge_base/getting_to_know_domo/index.qmd
        - contents:
          - knowledge_base/getting_to_know_domo/business_in_a_box/index.qmd
          section: Business In A Box
        - contents:
          - knowledge_base/getting_to_know_domo/domo_mobile/index.qmd
          section: Domo Mobile
        - contents:
          - knowledge_base/getting_to_know_domo/buzz/index.qmd
          section: Buzz
        - contents:
          - knowledge_base/getting_to_know_domo/free_domo/index.qmd
          section: Free Domo
        - contents:
          - knowledge_base/getting_to_know_domo/getting_started/index.qmd
          section: Getting Started
        - contents:
          - knowledge_base/getting_to_know_domo/goals_center/index.qmd
          section: Goals Center
        - contents:
          - knowledge_base/getting_to_know_domo/notifications_and_alerts/index.qmd
          section: Notifications And Alerts
        - contents:
          - knowledge_base/getting_to_know_domo/projects_and_tasks/index.qmd
          section: Projects And Tasks
        - contents:
          - knowledge_base/getting_to_know_domo/support_resources/index.qmd
          section: Support Resources
        - contents:
          - knowledge_base/getting_to_know_domo/user_profile/index.qmd
          section: User Profile
        section: Getting To Know Domo
      - contents:
        - knowledge_base/release_notes/index.qmd
        - contents:
          - knowledge_base/release_notes/archived_feature_release_notes/index.qmd
          section: Archived Feature Release Notes
        - contents:
          - knowledge_base/release_notes/current_release_notes/index.qmd
          section: Current Release Notes
        section: Release Notes
      - contents:
        - knowledge_base/training/index.qmd
        - contents:
          - knowledge_base/training/paid_training/index.qmd
          section: Paid Training
        - contents:
          - knowledge_base/training/selfservice_training/index.qmd
          - contents:
            - knowledge_base/training/selfservice_training/coursebuilder_14/index.qmd
            section: CourseBuilder 1.4
          - contents:
            - knowledge_base/training/selfservice_training/best_practices_resources/index.qmd
            section: Best Practices Resources
          - contents:
            - knowledge_base/training/selfservice_training/business_users_and_adoption_resources/index.qmd
            section: Business Users And Adoption Resources
          - contents:
            - knowledge_base/training/selfservice_training/onboarding_resources/index.qmd
            section: Onboarding Resources
          section: Self-Service Training
        section: Training
      - contents:
        - knowledge_base/transforming_data_in_domo/index.qmd
        - contents:
          - knowledge_base/transforming_data_in_domo/enterprise_stacker/index.qmd
          section: Enterprise Stacker
        - contents:
          - knowledge_base/transforming_data_in_domo/dataflow_management/index.qmd
          section: DataFlow Management
        - contents:
          - knowledge_base/transforming_data_in_domo/magic_etl/index.qmd
          - contents:
            - knowledge_base/transforming_data_in_domo/magic_etl/tiles/index.qmd
            section: Tiles
          section: Magic ETL
        - contents:
          - knowledge_base/transforming_data_in_domo/datafusion/index.qmd
          section: DataFusion
        - contents:
          - knowledge_base/transforming_data_in_domo/dataset_views/index.qmd
          section: DataSet Views
        - contents:
          - knowledge_base/transforming_data_in_domo/sdks/index.qmd
          section: SDKs
        - contents:
          - knowledge_base/transforming_data_in_domo/sql_dataflows/index.qmd
          section: SQL DataFlows
        - contents:
          - knowledge_base/transforming_data_in_domo/transformation_tips_and_tricks/index.qmd
          section: Transformation Tips And Tricks
        section: Transforming Data In Domo
      - contents:
        - knowledge_base/understanding_data/index.qmd
        - contents:
          - knowledge_base/understanding_data/data_literacy/index.qmd
          section: Data Literacy
        section: Understanding Data
      - contents:
        - knowledge_base/using_domo_apis/index.qmd
        - contents:
          - knowledge_base/using_domo_apis/developer_topics/index.qmd
          section: Developer Topics
        section: Using Domo APIs
      - contents:
        - knowledge_base/working_with_datasets_in_domo/index.qmd
        - contents:
          - knowledge_base/working_with_datasets_in_domo/automl_machine_learning/index.qmd
          section: AutoML (Machine Learning)
        - contents:
          - knowledge_base/working_with_datasets_in_domo/data_center_overview/index.qmd
          section: Data Center Overview
        - contents:
          - knowledge_base/working_with_datasets_in_domo/personalized_data_permissions_pdp/index.qmd
          section: Personalized Data Permissions (PDP)
        - contents:
          - knowledge_base/working_with_datasets_in_domo/sharing_access_to_datasets/index.qmd
          section: Sharing Access To DataSets
        section: Working With DataSets In Domo
      section: knowledge_base
    style: floating
  twitter-card: true
