project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]

  navbar:
    background: primary
    search: true
    left:
      - text: "Knowledge Base"
        href: knowledge_base/index.qmd

  sidebar:
    style: floating

    contents:
      - auto: "index.ipynb"
      - section: Test
        contents: test/*.ipynb

metadata-files: [nbdev.yml]
